# Base configs
baseurl: "https://lamsal9677.github.io/photography/"
# baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Photography by Sanskar Lamsal"
subtitle: "See the world through my eyes!"
author: "Sanskar Lamsal"
header:
 title: "Photography"
 subtitle: "by Sanskar Lamsal"
footer:
 name: "Hey there, my name is Sanskar"
 bio: "I am a developer and a tech aficionado from Nepal. Love making teeny tiny apps solving tiny problems in life and now learning photography."
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
# exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/lamsal9677"
  linkedin: "https://in.linkedin.com/in/lamsal9677"
  github: "https://www.github.com/lamsal9677"
