# Base configs
# baseurl: "https://lamsal9677.github.io/photo/"
baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

title: "Photography by Sanskar Lamsal"
subtitle: "See the world through my eyes!"
author: "Sanskar Lamsal"
header:
 title: "Photography"
 subtitle: "by Sanskar Lamsal"
footer:
 name: "Hi. I am Sanskar"
 bio: "Passionate photographer capturing nature, travel, and candid human moments with clean composition and thoughtful storytelling." 
social_urls:
  facebook: "https://www.facebook.com/lamsal9677/"
  instagram: "https://www.instagram.com/lamsal9677"